### PR TITLE
Customers can add products to a cart and view their cart's total cost

### PR DESCRIPTION
**Pull request by ethanschreur**
**What does this PR do?**
- This pull request allows customers to add products to a cart area and view the total cost.

**Description of the task to be completed** 
- Display an add-to-cart button under each product on the shop page
- Clicking that button will add the product's name, image, and price to the flask session which stores cart information. Clicking the add-to-cart button also turns the button to green and makes the add icon turn into a check icon
- The cart will be displayed on the cart page
- A total cost will be displayed below the cart section that is updated dynamically
- Every time the total cost changes, update the total cost that is displayed.
- The product can be removed from the cart by pressing the red button with the minus icon
- On the shop page, there will be a new link button in the navbar that takes customers to their cart page

**How should this  be tested**
- (On Windows) Run `. venv/scripts/activate` 
- `python run.py`
- Go to http://127.0.0.1:5000/login
- Enter the correct email and password and submit them
- View the dashboard page
- Press the products button
- Fill out the "add products" form and submit it
- Click on the added product in the products table
- Fill out the "add subproducts" form and submit it
- Go to http://127.0.0.1:5000/shop
- Press the add to cart button for the product  that you added
- Check that the button turns green and has a checkmark icon
- Go to HTTP://127.0.0.1:5000/cart
- Check if the total cost is accurate and that the product you added is in the cart section
- Increase and Decrease the amount value using the number input field making sure that the total cost is updating
- Press the red button in the cart section and confirm that the product is removed from the cart
- Go back to the shop page and confirm that the button next to the product price is blue again and is back to having an add icon instead of a checkmark icon

### CODE REVIEW

**Comment by ethanschreur** [comment]
The total cost is not working as I have envisioned so I removed the ready-for-review label.

**Comment by ethanschreur** [comment]
> The total cost is not working as I have envisioned so I removed the ready-for-review label.

@alexkayabula It should be ready to be reviewed now.

**Comment by alexkayabula** [comment]
I recommend that;
-  The `customer cart` is on a separate page.
-  On the carts page, when the quantity of the page is changed, the cart's total cost should change dynamically.

**Review by alexkayabula — CHANGES_REQUESTED** [review]
I recommend that;
-  The `customer cart` is on a separate page.
-  On the carts page, when the quantity of the page is changed, the cart's total cost should change dynamically.

**Comment by ethanschreur** [comment]
> I recommend that;
> 
> * The `customer cart` is on a separate page.
> * On the carts page, when the quantity of the page is changed, the cart's total cost should change dynamically.

@alexkayabula 

I agree that the cart should go on a separate page and will make those changes. 

I have a question, though, about your second point. In this branch, isn't the cart's total cost already dynamically changing every time the cart composition changes? Do you think it should be done differently?

**Comment by alexkayabula** [comment]
My bad, It actually does work dynamically.

**Review by alexkayabula — APPROVED** [review]
LGTM.

**Pull request merged**
